name: Deploy to shinyapps.io
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    container: 
      image: gvegayon/epiworldrshiny:latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        env:
          SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
          SHINY_USER: ${{ secrets.SHINY_USER }}
        run: |
          make build install deploy

